# Generated by Django 3.2.12 on 2022-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.TextField(choices=[('DR', 'Draft'), ('SB', 'Submitted'), ('RJ', 'Rejected'), ('PB', 'Published'), ('AR', 'Archived')], default='DR', max_length=2),
        ),
    ]
