# Generated by Django 3.2.12 on 2022-02-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='author',
        ),
    ]
